# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-


def build(bld):
    obj = bld.create_ns3_program('simple-network-example', ['lorawan'])
    obj.source = 'simple-network-example.cc'

    obj = bld.create_ns3_program('network-server-example', ['lorawan'])
    obj.source = 'network-server-example.cc'

    obj = bld.create_ns3_program('complete-network-example', ['lorawan'])
    obj.source = 'complete-network-example.cc'

    obj = bld.create_ns3_program('energy-model-example', ['lorawan'])
    obj.source = 'energy-model-example.cc'

    obj = bld.create_ns3_program('energy-single-device-example', ['lorawan', 'energy'])
    obj.source = 'energy-single-device-example.cc'

    obj = bld.create_ns3_program('network-analysis-capacitor', ['lorawan', 'energy'])
    obj.source = 'network-analysis-capacitor.cc'
